Demo :
	g++ -g -o cameraTest cameraTest.cpp ../cameraGetImageSource.cpp -I../include -I../ -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl

clean:
	rm cameraTest -rf